### PR TITLE
Add working (?) build script and GH Actions build workflow

### PR DESCRIPTION
**Pull request by AudunVN**
Short summary: Wanted to get this to build on my local machine to eventually try add a feature or two in my fork, so created a small build script and got it running in the half-finished existing build action. Haven't gotten quite as far as testing it beyond "it seems to build", but figured I'd make a quick draft pull request in case any of this is useful to somebody else upstream.

Kinda unsure how and what to test here, since there's been a lot of changes after the last version of mm2hook I've used. Assuming the build artifact might be missing quite a few Lua scripts, but the old test runner artifacts have expired a good while ago so it's unfortunately currently a bit hard for me to tell what should be included or not.

### CODE REVIEW

**Comment by AudunVN** [comment]
Managed to find [a release from last year](https://github.com/Fireboyd78/mm2hook/issues/123#issuecomment-1535209136) and the (in hindsight perhaps slightly obviously named) `bin/*/out` directory, so it's making quite a lot more sense now. Was wondering which *.dll was actually being hooked into, as dropping two new *.dll files into the MM2 install folder and expecting something to happen *did* seem a tiny bit optimistic. I should probably go get some sleep.

PS: Thank you (all) for your work on this, by the way! I've been coming back to MM2 on and off over the last twenty or so years, but this project had completely passed me by before yesterday.

**Comment by AudunVN** [comment]
Quick links for last test build:
- https://github.com/AudunVN/mm2hook/actions/runs/8770399623/job/24066919679
- https://github.com/AudunVN/mm2hook/actions/runs/8770399623/artifacts/1432871816 (zip of `bin/Release/out`)

Definitely not quite there yet, need to figure out which version of `discord_game_sdk.dll` to use - can't start the game without it even with `UseRichPresence=0` in mm2hook.ini, which I'm not sure if is the intended behavior.

---

EDIT: The `discord_game_sdk.dll` from both v3.2.1 and v2.5.6 at https://discord.com/developers/docs/game-sdk/getting-started seem to at least let the game start. The release build from the runner now seems to crash a tiny bit before the first loading bar is done, but unfortunately hard enough that `mm2hook.log` is abruptly cut off about a thousand lines in:

```
Installing 'aiPoliceOfficer' handler...
 - Installing callback [5FF9BDCA] for 'aiPoliceOfficer::DetectPerpetrator':
 - Description: Experimenting with making cops a little smarter about chasing people.
   => [call] 0053E057
 - Installing callback [5FF9BD38] for 'aiPoliceOfficer::DetectPerpetrator':
 - Description: Experimenting with making cops a little smarter about chasing opponents.
   => [call] 0053E11A
 - Insta
```

---

Debug build, same-ish time (unfortunately all I have at the moment, the off-screen bit of the error message never rendered)

image

**Comment by AudunVN** [comment]
Ah, caught it in mm2.log the second time (mostly just documenting my process with getting it to build and run here for later reference, since there's not a lot available online):

```
Midtown Madness 2 - Angel: 3393 / Nov  3 2000 14:34:22
AutoDetect: GUID=0, Description=dgVoodoo DirectX Wrapper, Name=display
  Created device in 148.3090 ms
  Total video memory: 64MB
  Enumerated display modes in 34.3983 ms
  Finished in 195.9271 ms
AutoDetect: GUID=5f6300b0, Description=Intel(R) Iris(R) Xe Graphics, Name=\\.\DISPLAY5
  Created device in 134.8665 ms
  Total video memory: 64MB
  Enumerated display modes in 36.0889 ms
  Finished in 182.0194 ms
AutoDetect: GUID=5f630158, Description=Intel(R) Iris(R) Xe Graphics, Name=\\.\DISPLAY1
  Created device in 140.2842 ms
  Total video memory: 64MB
  Enumerated display modes in 27.8497 ms
  Finished in 184.1629 ms
Playing movie now...
Done playing movie.
'.\MM2TEX.AR' is optimized archive.
Checksum file '.\MM2TEX.CHK' NOT loaded.
0.000413 seconds to read directory
'.\MM2CORE.AR' is optimized archive.
Checksum file '.\MM2CORE.CHK' NOT loaded.
0.000547 seconds to read directory
'.\MM2AUDEX.AR' is optimized archive.
Checksum file '.\MM2AUDEX.CHK' NOT loaded.
0.000219 seconds to read directory
'.\MM2AUD.AR' is optimized archive.
Checksum file '.\MM2AUD.CHKHK' NOT loaded.
0.000258 seconds to read directory
Heap MemUsed (Start of BeginPhase): 0.0M
Heap MemUsed (Just before CreateBankManager): 0.0M
Heap MemUsed (Just before loading screen): 0.0M
Heap MemUsed (Just after loading screen): 0.0M
Heap MemUsed (Just before InitAudioManager): 0.0M
DirSnd::SetDeviceRating device Primary Sound Driver Flags 3871
DirSnd::SetDeviceRating device Headphones (OontZ Angle 3U SS 890 Stereo) Flags 3871
DirSnd::SetDeviceRating device Headphones (Svive Leo Studio mic) Flags 3871
DirSnd::SetDeviceRating device Speakers (Realtek(R) Audio) Flags 3871
DirSnd::SetDeviceRating device Headset (OontZ Angle 3U SS 890 Hands-Free AG Audio) Flags 3871
Heap MemUsed (Just after InitAudioManager): 15.3M
Heap MemUsed (Just before GameInput): 15.3M
CreateDevice() failed - 80040154h  no JOYSTICK device found.
Heap MemUsed (At end of BeginPhase): 15.3M
Initializing ImGui
Error: [Lua] Error -- .\lua\main.lua:16: attempt to call a nil value (global 'Warningf')
stack traceback:
	[C]: in global 'Warningf'
	.\lua\main.lua:16: in metamethod '__newindex'
	.\lua\main.lua:107: in function 'startup'
Warning: Could not create aud\aud22\UIreplay.22k for agesound
Error: nodeGetBitmap() - 'ulock_amvpcab' not found
Error: nodeGetBitmap() - 'vpcab_desc' not found
City = San Francisco
SetupResChoices - interfaceChoice = 0, gfxInterfaceChoice = 2
City = San Francisco
Error: nodeGetBitmap() - 'ama_rank_desc' not found
Warning: DriverX profile loaded...
Error: DMusicObject::ScanDirectory ScanDirectory no files found
Error: DMusicObject::ScanDirectory ScanDirectory failed
Error: DMusicObject::Init() ScanDirectory() error
Lobby interface created or already created.
asNetwork::JoinLobbySession()
Heap MemUsed (Just before GameLoop): 16.6M
EAX=00000001 EBX=13a6f120 ECX=5d27502e EDX=00000004
ESI=13a60318 EDI=13a6f968 EBP=0019f388 ESP=0019f384
Exception 80000003 at EIP=0x5f87fe60 (ucrtbased._threadid + 0x40)
0x5f87fe60 (ucrtbased._threadid + 0x40)
0x5f87fff1 (ucrtbased._threadid + 0x1D1)
0x5f8912ca (ucrtbased.abort + 0x1A)
0x5ff98893 (luaopen_lfs + 0xDF523)
0x5ff96a81 (luaopen_lfs + 0xDD711)
0x5ff9694d (luaopen_lfs + 0xDD5DD)
0x5ff96728 (luaopen_lfs + 0xDD3B8)
0x5ff98cd5 (luaopen_lfs + 0xDF965)
0x5ff982cc (luaopen_lfs + 0xDEF5C)
0x5ffb5d46 (luaopen_lfs + 0xFC9D6)
0x5ff98351 (luaopen_lfs + 0xDEFE1)
0x5ff983a0 (luaopen_lfs + 0xDF030)
0x5ffb04e0 (luaopen_lfs + 0xF7170)
0x5ffb2aa2 (luaopen_lfs + 0xF9732)
0x5ff8eefd (luaopen_lfs + 0xD5B8D)
0x5ff8d868 (luaopen_lfs + 0xD44F8)
ExceptMain: Abnormal exit.
Max files open at once: 4
0. HANDLE=876e40
3. HANDLE=2
Fatal Error: memMemoryAllocator::FindHeap failed on ptr 13a7eb58
```

The same exact MM2 install launches and plays fine if I replace dinput.dll and dinput.pdb with a copy of mm2hook dated 2020-11-17 - which doesn't say all that much on its own, but it at least doesn't appear to be one of the generic "I'm struggling to get MM2 to run on modern Windows" issues that I usually associate `memMemoryAllocator` crashes with. Could be that building it with a very recent version of MSVC or a change in compiler options is coming back to bite me, though.

---

Release build crashes silently (no error messages) right before opening the main menu, after getting about 42 kb into AGE.log (with essentially all debug options turned on) and 42 kb into mm2hook.log. The sudden end in output is accurate to the log files.

`AGE.log`
```
Opening 'tune\vppanoz.info'...
Opening 'jpg\vppanoz_ulck.jpg'...
Opening 'texture\vppanoz_ulck.tex'...
Opening 'texture\vppanoz_ulck.tga'...
Opening 'texture\vppanoz_ulck.bmp'...
Opening 'jpg\vppanoz_ulck.jpg
```

`mm2hook.log`
```
Installing 'aiPoliceOfficer' handler...
 - Installing callback [5FD0BE37] for 'aiPoliceOfficer::DetectPerpetrator':
 - Description: Experimenting with making cops a little smarter about chasing people.
   => [call] 0053E057
 - Installing callback [5FD0BDA5] for 'aiPoliceOfficer::DetectPerpetrator
```

**Comment by AudunVN** [comment]
Both the latest debug and release builds do seem to launch and run fine with `EnableLua=0` in mm2hook.ini (as the logs would suggest by it being an exception in `luaopen_lfs`), so that's a start. Could be an issue that's not directly related to my changes to the compilation and build process, but not nearly familiar enough with mm2hook to speculate. Either way happy that it seems to build successfully to some degree!

**Comment by Dummiesman** [comment]
I'll merge this in since it seems to be a good base, and see if I can get things working.

**Pull request merged**
